name: ieum-green-mongo

services:
  mongo:
    image: mongo:7
    container_name: ${MONGO_CONTAINER_NAME}
    restart: unless-stopped

    ports:
      - "${HOST_BIND_IP}:${MONGO_HOST_PORT}:${MONGO_PORT}"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

    volumes:
      - ieum_mongo_data:/data/db

    networks:
      green_network:
        ipv4_address: ${MONGO_IP}

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --quiet -u ${MONGO_INITDB_ROOT_USERNAME} -p ${MONGO_INITDB_ROOT_PASSWORD} --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 }).ok' | grep -q 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  green_network:
    external: true
    name: ${GREEN_NETWORK}

volumes:
  ieum_mongo_data: